7042146 Implement ISIM project 7010609 installadm create-client for Sparc clients may not clean up old wanboot.conf file 7011274 installadm error usage message needs to be enhanced 7015125 the return value should be not be "0" when delete non-existent client 7015142 installadm should provide infomation what service name was created when without -n option 7021675 the Macro should be deleted after client was deleted 7034888 installadm list can probably stop displaying the port number 7037518 installadm delete-service doesn't clean up /tftpboot 7043712 RFE: clarify 'create-client' section in installadm to encompass a 'modify-client' condition 4564 delete-client returned successful when non-existent mac address passed in 6776 create-service should take imagepath with an option flag 6778 create-service should take imagepath as an optional argument 6812 create-service:Default service names are difficult to remember and not friendly 7380 installadm create-service prints to stderr when returning good status 8598 'installadm create-client' send error msgs to stdout instead of stderr in some cases 10853 create-service:Should consider removing /tftpboot/rm.<service|client> scripts 11293 delete-service: should check if clients are dependent on service 11537 create-service: Look to mounting boot archives via service configuration and not modifying /etc/vfstab 12812 create-client: image-path providence should be tracked through all error messages 13927 create-client allows same client for multiple services 14851 create-client should inherit boot options from install service 15170 /usr/lib/installadm/setup-dhcp returns 1 on failure or manual DHCP setup needed 15717 installadm list -n svc -m states error when no manifests 18157 create_client.py: AttributeError: 'module' object has no attribute 'AIImageError'
--HG--
rename : usr/src/lib/install_common/test/test_install_popen.py => usr/src/lib/install_common/test/test_install_common.py